#!/bin/bash

if [[ $# -eq 1 ]]; then
	CMD=~/bin/$1;
        if [[ -f "$CMD" ]]; then
		nano "$CMD";
		read -p "Change description: " DESC;
		cd ~/bin;
		git add . >/dev/null
		git commit -m "$DESC" >/dev/null
		git push >/dev/null
	else
		echo "Error: Command $1 does not exist" >&2;
	fi
else
        echo "Usage: $(basename $0) <CMD>" >&2;
fi
