#!/bin/bash

function commit() {
	git add .;
	git commit -m "$1";
	git push;
}

if [[ $# -eq 1 ]]; then
	CMD=~/bin/$1;
        if [[ -f "$CMD" ]]; then
		T=$(mktemp);
		cat "$CMD" > "$T";
		nano "$CMD";
		if ! diff -q "$T" "$CMD" &>/dev/null; then
			read -p "Change description: " DESC;
			cd ~/bin;
			commit "$DESC" &>/dev/null &
		fi
	else
		echo "Error: Command $1 does not exist" >&2;
	fi
else
        echo "Usage: $(basename $0) <CMD>" >&2;
fi
