#!/bin/bash

function commit() {
	git add .;
	git commit -m "removed $CMD ${DONE[*]}";
	git push;
}

if [[ $# -eq 0 ]]; then
        echo "Usage: $(basename 0) CMD..." >&2;
else
	DONE=();
	for I in "$@"; do
	        CMD="~/bin/$I";
        	if [[ -f "$CMD" ]]; then
                	if rm "$CMD"; then
				DONE+=("$1");
			fi;
	        else
        	        echo "Error: Command $1 does not exist" >&2;
	        fi;
	done;
	if [[ ${DONE[#]} -gt 0 ]]; then
		CMD="command"
		[[ ${DONE[#]} -gt 1 ]] && CMD="${CMD}s";
		cd ~/bin;
		commit &>/dev/null &
	fi;
fi;

